export const CuttingBoardRecipes = [
    { ingredients: { item: "farmerspizzeria:carbonara_pizza" }, result: [{ item: "farmerspizzeria:carbonara_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:cheese_pizza" }, result: [{ item: "farmerspizzeria:cheese_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:margarita_pizza" }, result: [{ item: "farmerspizzeria:margarita_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:meat_feast_pizza" }, result: [{ item: "farmerspizzeria:meat_feast_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:pepperoni_pizza" }, result: [{ item: "farmerspizzeria:pepperoni_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:abyssal_marinara_pizza" }, result: [{ item: "farmerspizzeria:abyssal_marinara_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:boscaiola_pizza" }, result: [{ item: "farmerspizzeria:boscaiola_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:charcoal_pizza" }, result: [{ item: "farmerspizzeria:charcoal_pizza_slice", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" },
    { ingredients: { item: "farmerspizzeria:dorblu_cheese_wheel" }, result: [{ item: "farmerspizzeria:dorblu_cheese_wedge", count: 4 }], tool: { tag: "farmersdelight:is_knife" }, is_block_type: false, sound: "use.mob.slime.big" }
];