import { DorbluCheese } from "./blocks/Cheese";
import { Pizza } from "./blocks/Pizza";
import { Dough } from "./blocks/Dough";
import { DoughPlace } from "./blocks/DoughPlace";
import { Keg } from "./blocks/keg/block";
import { KegEntity } from "./blocks/keg/entity";
import { Book } from "./items/Book";
import { BrewinandchewinBook } from "./items/BrewinandchewinBook";
new DorbluCheese();
new Pizza();
new Dough();
new DoughPlace();
new Book();
new BrewinandchewinBook();
new Keg();
new KegEntity();