import { DorbluCheese } from "./blocks/Cheese";
import { Pizza } from "./blocks/Pizza";
import { Dough } from "./blocks/Dough";
import { DoughPlace } from "./blocks/DoughPlace";
import { RecipeRegister } from "./register/Recipes";
new DorbluCheese();
new Pizza();
new Dough();
new DoughPlace();
new RecipeRegister();